# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnormFA_rowwiseCpp <- function(X, mu, Lambda, Psi_diag) {
    .Call(`_mixMuscleSynergy_dmvnormFA_rowwiseCpp`, X, mu, Lambda, Psi_diag)
}

faEMupdateCpp <- function(X, r, nIterFA) {
    .Call(`_mixMuscleSynergy_faEMupdateCpp`, X, r, nIterFA)
}

mfaTimeseriesCpp <- function(list_of_data, K, r, max_iter, nIterFA, tol, z_init = NULL) {
    .Call(`_mixMuscleSynergy_mfaTimeseriesCpp`, list_of_data, K, r, max_iter, nIterFA, tol, z_init)
}

dmvnormPCA_rowwiseCpp <- function(X, mu, W, sigma2) {
    .Call(`_mixMuscleSynergy_dmvnormPCA_rowwiseCpp`, X, mu, W, sigma2)
}

pcaEMupdateCpp <- function(X, r, nIter) {
    .Call(`_mixMuscleSynergy_pcaEMupdateCpp`, X, r, nIter)
}

pcaClosedFormCpp <- function(X, r) {
    .Call(`_mixMuscleSynergy_pcaClosedFormCpp`, X, r)
}

mpcaTimeseriesCpp <- function(list_of_data, K, r, max_iter, nIterPCA, tol, method = "EM", z_init = NULL) {
    .Call(`_mixMuscleSynergy_mpcaTimeseriesCpp`, list_of_data, K, r, max_iter, nIterPCA, tol, method, z_init)
}

